# Generated by Django 4.2.2 on 2023-06-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_remove_userprofile_img_profilo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='citazione',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
