# Generated by Django 4.2.2 on 2023-06-25 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_alter_review_movie_alter_review_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.CharField(max_length=500)),
            ],
        ),
    ]
