# Generated by Django 4.2.2 on 2023-06-25 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_citazione'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='citazione',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.citazione'),
        ),
    ]
