# Generated by Django 4.2.2 on 2023-06-25 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_userprofile_primo_accesso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='primo_accesso',
        ),
    ]
