# Generated by Django 4.2.2 on 2023-06-25 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_remove_userprofile_cognome_remove_userprofile_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.CharField(default='CIao', max_length=500),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='citazione',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='forum.citazione'),
        ),
    ]
