# Generated by Django 4.2.2 on 2023-06-26 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0013_userprofile_favorite_movies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='favorite_movies',
            field=models.ManyToManyField(related_name='favoritiesmovies', related_query_name='favoritiesmovies', to='forum.movie'),
        ),
    ]
