# Generated by Django 4.2.2 on 2023-06-26 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0015_remove_userprofile_favorite_movies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='citazione',
            field=models.ForeignKey(default=25, on_delete=django.db.models.deletion.CASCADE, to='forum.citazione'),
        ),
        migrations.CreateModel(
            name='Mipiace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
