# Generated by Django 4.2.2 on 2023-06-26 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0016_alter_userprofile_citazione_mipiace'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mipiace',
        ),
    ]
