# Generated by Django 4.2.2 on 2023-06-26 12:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0017_delete_mipiace'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='mipiace',
            field=models.ManyToManyField(related_name='mipiace', related_query_name='mipiace', to=settings.AUTH_USER_MODEL),
        ),
    ]
