# Generated by Django 4.2.2 on 2023-06-26 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0018_review_mipiace'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mipiace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='review',
            name='mipiace',
            field=models.ManyToManyField(to='forum.mipiace'),
        ),
    ]
