# Generated by Django 4.2.2 on 2023-06-26 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0020_commento_remove_review_mipiace_delete_mipiace_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='commenti',
        ),
        migrations.AddField(
            model_name='commento',
            name='review',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='forum.review'),
        ),
    ]
