# Generated by Django 4.2.2 on 2023-06-26 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0021_remove_review_commenti_commento_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commento',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.review'),
        ),
    ]
