# Generated by Django 4.2.2 on 2023-06-26 15:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0024_userprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='likes',
            field=models.ManyToManyField(related_name='review_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
