# Generated by Django 4.2.2 on 2023-06-27 08:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0026_comment_delete_commento'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', to='forum.userprofile'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 27, 8, 34, 1, 24078, tzinfo=datetime.timezone.utc)),
        ),
    ]
