# Generated by Django 4.2.2 on 2023-07-02 09:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0034_remove_poll_group_remove_poll_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='date_published',
            field=models.DateField(default=datetime.datetime(2023, 7, 2, 9, 21, 1, 711652, tzinfo=datetime.timezone.utc)),
        ),
    ]
